services:
  # web: 
  #  depends_on:
  #   - postgres_db
  #  build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #  image: djnango-k8s:v1
  #  environment:
  #     - PORT=8020
  #  env_file:
  #     - ./web/.env
  #  ports:
  #      - "8001:8020"  
  #  command: bash -c "chmod +x /app/migrate.sh && /app/migrate.sh && /app/entrypoint.sh"
  postgres_db:
      image: postgres
      command: -p 5433
      restart: always
      expose:
        - 5433
      ports:
        - "5433:5433"
      env_file:
        - ./web/.env  
      volumes:
        - postgres_data:/var/lib/postgresql/data
  redis_db:
      image: redis
      restart: always
      expose:
        - 6388
      ports:
        - "6388:6388"
      volumes:
        - redis_data:/data
      entrypoint: redis-server --appendonly yes --port 6380
volumes:
  postgres_data:
  redis_data:
